foundry_sources += files([
  'foundry-ci-artifact.c',
  'foundry-ci-enums.c',
  'foundry-ci-job.c',
  'foundry-ci-manager.c',
  'foundry-ci-pipeline.c',
  'foundry-ci-provider.c',
  'foundry-ci-run.c',
  'foundry-ci-run-options.c',
])

foundry_headers += files([
  'foundry-ci-artifact.h',
  'foundry-ci-enums.h',
  'foundry-ci-job.h',
  'foundry-ci-manager.h',
  'foundry-ci-pipeline.h',
  'foundry-ci-provider.h',
  'foundry-ci-run.h',
  'foundry-ci-run-options.h',
])

foundry_include_directories += include_directories('.')
