foundry_private_sources += files([
  'plugin.c',
  'plugin-gitlab-ci-component.c',
  'plugin-gitlab-ci-compiler.c',
  'plugin-gitlab-ci-job.c',
  'plugin-gitlab-ci-pipeline.c',
  'plugin-gitlab-ci-run.c',
  'plugin-gitlab-ci-config-loader.c',
  'plugin-gitlab-ci-context.c',
  'plugin-gitlab-ci-error.c',
  'plugin-gitlab-ci-expression.c',
  'plugin-gitlab-ci-provider.c',
  'plugin-gitlab-ci-runner.c',
  'plugin-gitlab-ci-yaml.c',
])

foundry_deps += [
  dependency('libsoup-3.0'),
]
